# Generated by Django 5.2.5 on 2025-09-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_app', '0005_taskcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
